### ISSUE TITLE
Busy loop recreating state.json on invalid .pcap files

### ISSUE THREAD

**Issue by peace-maker** [spq/pkappa2#18]
When uploading an empty or otherwise invalid .pcap file, pkappa2 will try to parse it over and over, creating and deleting a state.json file in the process.

**Comment by peace-maker** [comment]
The problem appears to be that the problematic file isn't removed from the `mgr.importJobs` list on failure.

Here it returns that `0` files were processed when one of the pcaps in the batch fail to parse.
https://github.com/spq/pkappa2/blob/73e39cd5aa79286bcd53d57e04a40b721a6713c4/internal/index/builder/builder.go#L103-L106

The caller only logs the error and continues anyway
https://github.com/spq/pkappa2/blob/73e39cd5aa79286bcd53d57e04a40b721a6713c4/internal/index/manager/manager.go#L362-L365

And eventually tries to remove processed files from the job queue, but since `processedFiles` is `0` this will go on forever.
https://github.com/spq/pkappa2/blob/73e39cd5aa79286bcd53d57e04a40b721a6713c4/internal/index/manager/manager.go#L404-L410

The error handling of the `Builder.FromPcap` function seems bogous. Are there any errors where it's useful to retry? Otherwise I'd just ignore the failing files and continue instead of return. All the other early returns need to be looked at as well.

**Comment by peace-maker** [comment]
pkappa2 refuses to start after it received an invalid pcap once as well. So the problematic pcaps need to be ignored during startup as well. I don't know if we want to delete them upon receival, but maybe moving into an "invalid" folder for later analysis might be good?

https://github.com/spq/pkappa2/blob/73e39cd5aa79286bcd53d57e04a40b721a6713c4/internal/index/builder/builder.go#L53-L56

**Comment by spq** [comment]
i have used some of your patches but left out some that I don't think are needed to fix this and modified some others to have as small an impact as possible.
could you confirm that this is fixed?

**Comment by peace-maker** [comment]
It appears to be solved now. Thank you!
