### ISSUE TITLE
Queries using sub-query variables match wrong streams

### ISSUE THREAD

**Issue by peace-maker** [spq/pkappa2#197]
The example query from the Help page matches unexpected streams.
`@sub:cdata:"(?P<flag>ENO[A-Za-z0-9+\/=]{48})" sdata:"@sub:flag@"`

![grafik](https://github.com/user-attachments/assets/a0dc49ae-a3f3-4649-a4ed-d4e49af39f7f)

I'd expect that query to match all streams where the client sent a flag and the server echoed it back. The matched streams don't have the client send the flag though.

**Comment by spq** [comment]
It's a long time ago when I wrote this feature, but IIRC the sub-query feature does something else than what you think it does.
The query you show will search all flags that are sent by a client in any stream and then do the actual search for all steams where a server sent one of these flags.
In SQL, this would be something like a JOIN.

Please reopen if I missed something!
