### ISSUE TITLE
Server not responsive on certain high-load queries

### ISSUE THREAD

**Issue by libnewton** [spq/pkappa2#20]
When executing certain queries the server (even when having very high specs at hand) becomes unresponsive and is overloaded.

Proposed Solution: Cap execution time and / or resource usage for each query and add a way to abort an query

**Comment by spq** [comment]
the intention is to have the server responsive with multiple parallel queries, is the server really not responding or is it the browser or so?

**Comment by spq** [comment]
Thanks!
I will close the bug for now - please reopen when you have additional information, I just tested locally and was able to perform multiple longer running queries in parallel.
