### ISSUE TITLE
"Search Selection" searches for one byte before the selection

### ISSUE THREAD

**Issue by peace-maker** [spq/pkappa2#29]
When selecting bytes in the output and pressing `Search Selection`, the selection is one too large.

Selecting `/bla` in `GET /bla HTTP/1.1` would cause the query to include the space beforehand `cdata:"\x{20}\x{2F}bla"`.

Printable characters should be inserted plain without `\x{XX}` for readability too.

**Comment by spq** [comment]
you don't use chrome, do you?
in chrome, only the text is searched for, in firefox sometimes the char before and sometimes the char after is searched for.
the list of characters that don't need escaping could be extended, true - however we still have to escape "regex active" chars, is this a good set of chars to add: " !#$%&',-/:;<=>^_`~"

**Comment by spq** [comment]
i fixed it

**Comment by peace-maker** [comment]
Nope, I've tested in Firefox indeed. I didn't think it'd be browser specific. The list looks good, thank you!
