### ISSUE TITLE
Assume `data:` prefix if query couldn't be parsed at all

### ISSUE THREAD

**Issue by peace-maker** [spq/pkappa2#34]
Allow to search more intuitively by not requiring to learn the query language to do a quick regex search in the pcaps.
If parts of the query are valid syntax, the query should still fail to catch typos. But queries like `GET /bla` should silently be treated like `data:"GET /bla"`.

**Comment by spq** [comment]
maybe we can instead ask in the ui if you meant data:"..." and have a button in the error message to use that?
still has the advantage of you don't have to learn but teaches you as well and removes risks for accidentally interpreting something wrongly and not returning a result without telling you why.
also we could add a clippy :D

**Comment by peace-maker** [comment]
Or have simple and advanced query modes in the UI, where you can switch to advanced queries to use the full query language. We could still translate the simple regex query to `data:"query"` when switching to the advanced query mode.
When playing A&D CTFs with newcomers, I've observed them only wanting to search for data anyway, so the more intricate query possibilities weren't used by default. That correction suggestion in the error message would already help when forgetting the syntax though I guess.

The "did you mean" helper link in the error message / clippy is still a nice idea for the advanced view.

**Comment by spq** [comment]
i think this is good enough for now, this also teaches new users the format, so i like it...
